---
apiVersion: v1
kind: Service
metadata:
  name: dockerhub-exporter
  labels:
    app: dockerhub-exporter
spec:
  type: ClusterIP
  ports:
  - port: 2113
    protocol: TCP
    targetPort: 2113
  selector:
    app: dockerhub-exporter